name: nga
description: "Next Generation Austria - Politische Partizipation für Österreichs Zukunft"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP Requests
  http: ^1.1.0
  dio: ^5.4.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Charts für Poll Results
  fl_chart: ^1.0.0
  
  # Navigation
  go_router: ^16.0.0
  
  # Loading & Snackbars
  flutter_spinkit: ^5.2.0
  
  # Date/Time
  intl: ^0.20.2
  flex_color_scheme: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# Unter der flutter: Sektion:
flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Icons


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/nga_logo.png"